# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: OpenSearch Lucene snapshots

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ref:
        default: 'main'
        
jobs:
  build:

    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Checkout Lucene
      uses: actions/checkout@v2
      with:
        repository: 'apache/lucene'
        path: lucene
        ref: ${{ github.event.inputs.ref }}

    - name: Set hash
      working-directory: ./lucene
      run: |
        echo "::set-output name=REVISION::$(git rev-parse --short HEAD)"
      id: version
      
    - name: Publish Lucene
      working-directory: ./lucene
      run: ./gradlew publishJarsPublicationToMavenLocal -Pversion.suffix=snapshot-${{ steps.version.outputs.REVISION }}
      
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::126083459307:role/GitHubActionsRelease
        aws-region: us-west-2

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 cp ~/.m2/repository/org/apache/lucene/ s3://test.handalm/snapshots/lucene/org/apache/lucene/  --recursive --no-progress

