# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-build:
    runs-on: 'ubuntu-18.04'
    steps:
        - name: Create Issue On Push Failure
          run: |
            touch ./failure.md
            echo ### Gradle Check (Jenkins) Run Completed with: >> ./failure.md
            echo * **RESULT:** ${{ env.result }} :x: ${{ env.test_failures }} >> ./failure.md
            echo * **URL:** ${{ env.workflow_url }} >> ./failure.md
            echo * **CommitID:** ${{ env.pr_from_sha }}  >> ./failure.md

        - name: Create Issue On Push Failure
          uses: peter-evans/create-issue-from-file@v4
          with:
            title: Post-Merge Gradle Check Failure.
            content-filepath: ./failure.md
            labels: test-failur
            

