# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  issues: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue On Push Failure
      - uses: actions/checkout@v2
      - uses: dblock/create-a-github-issue@v3
        env:
          WORKFLOW_URL: testurl
          PR_FROM_SHA: commitId
        with:
          filename: .github/ISSUE_TEMPLATE/failed_check.md
            

