on: [workflow_dispatch]
name: Create an issue on push
permissions:
  contents: read
  issues: write 
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: dblock/create-a-github-issue@v3
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_URL: testurl
          PR_FROM_SHA: commitId
            with:
              filename: .github/ISSUE_TEMPLATE/failed_check.md
              
      - name: Step2
              
